### ISSUE TITLE
Add Jonathan Levin's tools

### ISSUE THREAD

**Issue by theevilbit** [kohnakagawa/cidre-vm#7]
This might require some work, and I might do PRs for them, but leaving this here so we are aware. It would be nice to add all of these. Most of them will require recompile.

https://newosxbook.com/src.jl?tree=&file=/listings
https://newosxbook.com/downloads.html
https://newosxbook.com/code.html

**Comment by kohnakagawa** [comment]
Thank you! I'm currently working on this issue.

**Comment by kohnakagawa** [comment]
I have added the following Jonathan Levin's tools by updating the Brewfile.

- Process Monitor
- File Monitor
- hfsleuth
- simplistic

There are other tools that have not been added, but I would like to add only those tools that are useful for macOS malware analysis. I'd close this issue for now, but if some tools are missing, please reopen this issue.

**Comment by theevilbit** [comment]
Can we add this?
https://newosxbook.com/tools/disarm.html

nightly build:
http://newosxbook.com/tools/disarm

**Comment by kohnakagawa** [comment]
It looks good. I have added this tool!
